# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeRequestState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_number', models.CharField(max_length=30)),
                ('started_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('name', models.CharField(help_text="What's your full name?", max_length=255)),
                ('tree_choice', models.IntegerField(choices=[('1', 'Live Oak'), ('2', 'Nuttall Oak'), ('3', 'Magnolia'), ('4', 'Winged Elm'), ('5', 'Eagleson Holly'), ('6', 'Yauppon Holly'), ('7', 'Crape Myrtle'), ('8', 'Trumpet Tree'), ('9', 'Japanese Blueberry')], help_text='What kind of tree would you like? Pick a number.\n1:Live Oak\n2:Nuttall Oak\n3:Magnolia\n4:Winged Elm\n5:Eagleson Holly\n6:Yauppon Holly\n7:Crape Myrtle\n8:Trumpet Tree\n9:Japanese Blueberry', null=True)),
                ('street_address', models.CharField(help_text='What street is your house on?', max_length=255)),
                ('city', models.CharField(help_text='In what city?', max_length=255)),
                ('postal_code', models.CharField(help_text='What postal code?', max_length=255)),
                ('email_address', models.EmailField(help_text="What's your email address?", max_length=254, null=True)),
            ],
        ),
    ]
