# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treerequeststate',
            name='city',
            field=models.CharField(help_text='In what city? It would be very unusual if you answered something other than "Orlando".', max_length=255),
        ),
        migrations.AlterField(
            model_name='treerequeststate',
            name='street_address',
            field=models.CharField(help_text='What number and street is your house at? ex, "123 Maple Ave"', max_length=255),
        ),
    ]
