# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbot_one_person_one_tree', '0002_auto_20161007_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treerequeststate',
            name='tree_choice',
            field=models.IntegerField(choices=[('1', 'Live Oak'), ('2', 'Nuttall Oak'), ('3', 'Magnolia'), ('4', 'Winged Elm'), ('5', 'Tabebuia Ipe (Pink Trumpet Tree)'), ('6', 'Eagleson Holly'), ('7', 'Yauppon Holly'), ('8', 'Crape Myrtle'), ('9', 'Yellow Tabebuia (Trumpet Tree)'), ('10', 'Elaeocarpus (Japanese Blueberry)')], help_text='What kind of tree would you like? Pick a number.\n1:Live Oak\n2:Nuttall Oak\n3:Magnolia\n4:Winged Elm\n5:Tabebuia Ipe (Pink Trumpet Tree)\n6:Eagleson Holly\n7:Yauppon Holly\n8:Crape Myrtle\n9:Yellow Tabebuia (Trumpet Tree)\n10:Elaeocarpus (Japanese Blueberry)', null=True),
        ),
    ]
