# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbot_one_person_one_tree', '0003_auto_20161010_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treerequeststate',
            name='city',
        ),
        migrations.AlterField(
            model_name='treerequeststate',
            name='street_address',
            field=models.CharField(help_text='What number and street is your house at? It has to be inside Orlando. ex, "123 Maple Ave"', max_length=255),
        ),
    ]
